export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_DOGS_BY_API = "GET_DOGS_BY_API";
export const GET_DOGS_BY_DB = "GET_DOGS_BY_DB";
export const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME";
export const GET_DOG_BY_ID = "GET_DOG_BY_ID";
export const GET_DOGS_BY_TEMPERAMENTS = "GET_DOGS_BY_TEMPERAMENTS";
export const POST_DOG_CREATE = "POST_DOG_CREATE";
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
export const ORDER_BY_NAME = "ORDER_BY_NAME";

// {
//     GET_DOGS,
//     GET_TEMPERAMENTS,
//     GET_DOGS_CREATED,
//     GET_DOGS_BY_API,
//     GET_DOGS_BY_DB, 
//     GET_DOGS_BY_NAME, 
//     GET_DOG_DETAIL
// }